# Generated by Django 3.1.5 on 2021-01-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyphrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyphrase_content', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('is_on_wiki', models.BooleanField(default=False)),
                ('wiki_link', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(max_length=2000)),
            ],
        ),
    ]
